// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh5tAUNjzy-LBXczVm0ZDD8wGvFNbF_1s',
    appId: '1:1094983580080:web:f176490aef9138fa2afe75',
    messagingSenderId: '1094983580080',
    projectId: 'ajari-e-learning-5dfdb',
    authDomain: 'ajari-e-learning-5dfdb.firebaseapp.com',
    storageBucket: 'ajari-e-learning-5dfdb.firebasestorage.app',
    measurementId: 'G-Q8S7C4W9PW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIYJJRElvGkRLsxh8opQijITQqEVf5OiI',
    appId: '1:1094983580080:android:cae19a7d706f19f52afe75',
    messagingSenderId: '1094983580080',
    projectId: 'ajari-e-learning-5dfdb',
    storageBucket: 'ajari-e-learning-5dfdb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNghg7sNxCTkzqOUU5-ixoJHYHjD4byIY',
    appId: '1:1094983580080:ios:ad7b5eb3ab8e770a2afe75',
    messagingSenderId: '1094983580080',
    projectId: 'ajari-e-learning-5dfdb',
    storageBucket: 'ajari-e-learning-5dfdb.firebasestorage.app',
    iosBundleId: 'com.example.uas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNghg7sNxCTkzqOUU5-ixoJHYHjD4byIY',
    appId: '1:1094983580080:ios:ad7b5eb3ab8e770a2afe75',
    messagingSenderId: '1094983580080',
    projectId: 'ajari-e-learning-5dfdb',
    storageBucket: 'ajari-e-learning-5dfdb.firebasestorage.app',
    iosBundleId: 'com.example.uas',
  );
}
